name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Resourcegroup rg-githubactions
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: 59b9446c-2c8a-4a25-88bd-f75261beef88
          region: Germany West Central
          template: ./arm-templates/resourcegroup.json
          parameters: 
            location="Germany West Central"
            resourceGroupName=rg-githubactions
          deploymentName: rg-githubactions

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId: 59b9446c-2c8a-4a25-88bd-f75261beef88
          template: ./arm-templates/storageaccount.json
          parameters: 
            ./arm-templates/storageaccount.parameters.json
            storageAccountName=globostg002mfj
            location="Germany West Central"
          deploymentMode: incremental

#      - run: echo ${{ steps.storageAccountDeploy.outputs.BlobUri }}

