name: "Bicep Deploy Workflow"

on:
  push:
    branches:
      - main

env:
  subscriptionId: 59b9446c-2c8a-4a25-88bd-f75261beef88

jobs: 
  bicepAzCliDeploy:
    name: Bicep AZ CLI Deploy Job
    runs-on: ubuntu-latest

    env:
      resource_group_name: rg-bicep-azcli-github
      location: East US

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds:  ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group
        uses: Azure/cli@1.0.4
        with:
          Inlinescript: |
            az deployment sub create \
            --name ${{env.resource_group_name}} \
            --location "${{env.location}}" \
            --template-file ./bicep-templates/resourcegroup.bicep \
            --parameters \
            resourceGroupName=${{env.resource_group_name}} \
            location="${{env.location}}"

      - name: Deploy Virtual Network
        uses: Azure/cli@1.0.4
        with:
          Inlinescript: |
            az deployment group create \
            --resource-group ${{env.resource_group_name}} \
            --template-file ./bicep-templates/virtualnetwork.bicep \
            --parameters \
            vNetPrefix=bicepazcli \
            location="${{env.location}}"

  bicepARMDeployAction:
    name: Bicep ARM-Deploy Deploy Job
    runs-on: ubuntu-latest

    env:
      resource_group_name: rg-bicep-armdeploy-github
      location: East US

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds:  ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy resource group
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          region: "${{env.location}}"
          subscriptionId: ${{env.subscriptionId}}
          deploymentName: ${{env.resource_group_name}}
          template: ./bicep-templates/resourcegroup.bicep
          parameters:
            resourceGroupName=${{env.resource_group_name}} 
            location="${{env.location}}"

      - name: Deploy vnet
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: ${{env.resource_group_name}}
          subscriptionId: ${{env.subscriptionId}}
          template: ./bicep-templates/virtualnetwork.bicep
          parameters: 
            vNetPrefix=biceparmdeploy
            location="${{env.location}}"